# ----------------------------------------------------------------- #
#                                                                   #
#                     BOMBERMAN SAMPLE CONFIG                       #
#                                                                   #
#                        sample_config.yml                          #
#                                                                   #
#                                                                   #
#   This file contains the default configuration.                   #
#   You can overwrite anything by setting the value in config.yml   #
#                                                                   #
#   Note: this file will be reset every time the server reloads     #
#                                                                   #
# ----------------------------------------------------------------- #


# Directory where schematics should be saved
# Note: configuring where WorldEdit schematics are loaded from is in the WorldEdit config
schematics-save:
  # A location to copy any schematics packaged with the jar
  builtin: schematics/builtin
  # A location to save schematics made from the wand selection
  custom: schematics/custom
# Directory where Game config data is saved
game-saves: games
# Directories to save temporary data
temp-data:
  # Cached game data
  game: temp/game
  # Player inventories and spawn information
  player: temp/player
# Where the translated text file is
# The default messages are here:
# https://github.com/mdsimmo/Bomberman/blob/master/src/main/resources/english.yml
language: 'messages.yml'

# Default settings for new games
# Changing these values will NOT effect existing games.
# Alter existing games' settings by editing games/<name>.yml
default-game-settings:
  ==: io.github.mdsimmo.bomberman.game.GameSettings

  # How many lives each player gets
  lives: 3
  # The item type to use for bomb size calculations
  power: minecraft:gunpowder
  # The block type which explodes
  bomb: minecraft:tnt
  # The block type used for flames from tnt
  fire: minecraft:fire

  # What each player spawns in the game with
  # The item order is preserved in players inventory; pad with nulls
  initial-items:
  - ==: org.bukkit.inventory.ItemStack
    v: 2230
    type: TNT
    amount: 3

  # How long before tnt explodes
  fuse-ticks: 40
  # The duration that tnt flames should remain for
  fire-ticks: 20
  # How long before a player can take a second hit
  immunity-ticks: 21

  # What each block type should drop.
  # Each set of materials has a list of Item stacks mapped to a weighting.
  # Materials without an entry will not drop anything.
  loot-table:
  - blocks:
    - minecraft:snow_block
    - minecraft:dirt
    - minecraft:sand
    loot:
    - weight: 4   # The relative weighting of choosing this item
      item:         # What item to drop
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: TNT
    - weight: 100
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: AIR
        amount: 0   # amount 0 means "no drop"
    - weight: 3
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: GUNPOWDER
    - weight: 1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:healing
    - weight: 1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:strong_swiftness
    - weight: 1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:invisibility

    # Below is a second set of blocks with different loot.
    # Add as many sets as you want
  - blocks:
    - minecraft:gravel
    loot:
    - item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: TNT
      weight: 1.0
    - item:
        ==: org.bukkit.inventory.ItemStack
        v: 2230
        type: AIR
        amount: 0
      weight: 10.0


  # Bomberman has four types of blocks:
  #  1. indestructible: tnt will not effect the block
  #  2. destructible: tnt will destroy the block, but progress no further
  #  3. pass-keep: tnt will pass through the block without changing the blocks state.
  #                Players inside pass-keep blocks will still be hit
  #  4. pass-destroy: tnt will pass through the block, ignite the block, then change into air
  #
  # Unless set otherwise:
  #  * All solid blocks are indestructible
  #  * All non-solid blocks are pass-destroy.
  # A solid block is defined as a block that has any hitbox that blocks the players movement
  #
  # All types will drop loot when destroyed if they are assigned in loot-table
  #
  # The assigned tnt fire type and air types are always pass-destroy and cannot be altered
  #
  # Note: The in-game configuration gui will "smart add" similar material ids (e.g wall_sign and sign).
  #  You have to add similar ids manually here

  # Blocks tnt will explode the first block of
  # Generally, blocks that are in the loot-table should be destructible
  # Removing tnt from destructible means tnt explosions will not chain together
  destructible:
  - minecraft:tnt
  - minecraft:snow_block
  - minecraft:dirt
  - minecraft:sand
  - minecraft:gravel

  # Blocks tnt cannot touch.
  # All solid blocks included by default
  indestructible: []

  # Blocks tnt will pass through, but not alter.
  # You might like to put your sensitive redstone, tripwires, signs, etc here
  pass-keep: []

  # Blocks tnt will pass through, ignite, and destroy
  # All non-solid blocks included by default
  # Will always include air types and the tnt fire type
  pass-destroy: []